FROM node:11.9.0 as behaviors

ENV DOCKER="1"

WORKDIR /build

RUN git clone -b tweaks https://github.com/webrecorder/wr-behaviors.git

WORKDIR /build/wr-behaviors

RUN yarn install && yarn run build-behaviors


FROM node:11.9.0 as behaviorsAPI

EXPOSE 3030

ENV WR_BEHAVIOR_DIR="/app/dist" WR_BEHAVIOR_METADATA_PATH="/app/dist/behaviorMetadata.js"

WORKDIR /app

COPY --from=behaviors /build/wr-behaviors .

CMD ["node", "--harmony-await-optimization", "./api/run.js"]
